on:
  push:
    branches: 
      - "master"
      - "release/*"
jobs:
  release-to-ruby-gems:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: setup release credentials
        env:
          RELEASE_TOKEN: ${{ secrets.RUBY_GEMS_TOKEN }}
        run: |
          rm -rf ~/.gem/credentials
          mkdir -p ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":rubygems_api_key: ${RELEASE_TOKEN}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
      - name: release package
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |
          rm -rf ~/.git-credentials
          echo "https://tianhaoz95:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
          git config --global user.email "jacksonzhou666@gmail.com"
          git config --global user.name "Tianhao Zhou"
          bundle install
          bundle exec rake install
          bundle exec rake release
